config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :new, :destroy]

  resource :user, only: [:show, :new, :create]

  resources :albums, only: [:create, :destroy, :edit, :show, :update]

  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :band_id, presence: true
  validates :live, presence: true

  belongs_to :band,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: 'Band'

  has_many :tracks,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: 'Track'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: 'Album'
end

app/models/track.rb
class Track < ApplicationRecord
  validates :album_id, presence: true
  validates :bonus, presence: true
  validates :lyrics

  belongs_to :album,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: 'Album'
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates :session_token, uniqueness: true, presence: true
  validates :password_digest, uniqueness: true, presence: true
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    Bcrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return nil if @user.nil?
    @user.is_password?(password) ? @user : nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !session[:session_token].nil?
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = user.find_by_credentials(params[:user][:email], params[:user][:password])
    if user.nil?
     flash[:errors] = ["Invalid credentials."]
     render :new
    else
      session[:session_token] = @user.reset_session_token!
    end
    redirect_to user_url
  end

  def new
    render :new
  end

  def destroy
    @user.reset_session_token
    session[:session_token] = nil
    redirect_to user_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.ensure_session_token
      redirect_to new_session_url
    else
      #ask about flash.now
      render :new
    end
  end

  def show
    # @user = User.find_by(email: email)
    render :show
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>In Yeezus We Trust</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <div>
    <%if current_user.nil? %>
      <%= link_to "Log In", user_url, method: :post %>
      <%= link_to "Sign Up", new_user_url, method: :get %>
    <% else %>
      <%= button_to "Peace Out", session_url, method: :delete %>
    <% end  %>
  </div>


  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up Page</h1>


<form action="<%= user_url %>" method="POST">
  <input type="hidden" name="authenticity_token"
  value=" <%= form_authenticity_token %>">

  <label  for"email">Email:</label>
  <input  type="text"
          name="user[email]"
  <label  for="password">Password</label>
  <input  type="password"
          name="user[password]">
  <input  type="submit">
</form>

app/views/users/show.html.erb
<h1>Welcome! <% @user %></h1>
<p>Find me in app/views/users/show.html.erb</p>